/* Brewfreund product catalog. Static data — no backend. */

const PRODUCTS = [
  {
    id: "schwarzwald-espresso",
    sku: "BF-ESP-001",
    name: "Schwarzwald Espresso",
    category: "espresso",
    roast: "dark",
    price: 14.90,
    origin: "Blend — Brazil & Sumatra",
    rating: 4.8,
    ratingCount: 214,
    notes: ["Dark chocolate", "Toasted hazelnut", "Molasses"],
    description: "Our flagship espresso, built for a syrupy shot with a long, cocoa-toned finish. Roasted slow in small batches at our Freiburg roastery to keep the bitterness low and the body full.",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1000&q=80",
    format: "250g whole bean",
    altitude: "900–1,300m",
    process: "Washed & natural blend"
  },
  {
    id: "alpengluehen-blend",
    sku: "BF-FIL-002",
    name: "Alpenglühen Blend",
    category: "filter",
    roast: "medium",
    price: 13.50,
    origin: "Blend — Ethiopia & Colombia",
    rating: 4.7,
    ratingCount: 168,
    notes: ["Red apple", "Brown sugar", "Orange zest"],
    description: "A bright, balanced filter blend named for the pink alpenglow that hits the Black Forest at dawn. Equally at home in a pour-over or a drip machine.",
    image: "https://images.unsplash.com/photo-1442550528053-c431ecb55509?auto=format&fit=crop&w=1000&q=80",
    format: "250g whole bean",
    altitude: "1,400–2,000m",
    process: "Washed"
  },
  {
    id: "kilimanjaro-sonnenaufgang",
    sku: "BF-FIL-003",
    name: "Kilimanjaro Sonnenaufgang",
    category: "filter",
    roast: "light",
    price: 16.90,
    origin: "Single origin — Tanzania",
    rating: 4.9,
    ratingCount: 96,
    notes: ["Blackcurrant", "Bergamot", "Honey"],
    description: "A lively single-origin from the volcanic soils around Kilimanjaro. Roasted light to preserve its floral, tea-like character — best brewed as a pour-over.",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=80",
    format: "250g whole bean",
    altitude: "1,600–1,900m",
    process: "Washed"
  },
  {
    id: "sumatra-mandheling-reserve",
    sku: "BF-ESP-004",
    name: "Sumatra Mandheling Reserve",
    category: "espresso",
    roast: "dark",
    price: 17.50,
    origin: "Single origin — Indonesia",
    rating: 4.6,
    ratingCount: 132,
    notes: ["Cedar", "Dark caramel", "Earthy spice"],
    description: "A full-bodied, low-acid single origin processed the traditional Sumatran wet-hulled way. Heavy, syrupy and built for milk drinks.",
    image: "https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&w=1000&q=80",
    format: "250g whole bean",
    altitude: "1,100–1,500m",
    process: "Wet-hulled"
  },
  {
    id: "morgenlicht-decaf",
    sku: "BF-DEC-005",
    name: "Morgenlicht Decaf",
    category: "decaf",
    roast: "medium",
    price: 15.90,
    origin: "Single origin — Colombia",
    rating: 4.5,
    ratingCount: 87,
    notes: ["Milk chocolate", "Walnut", "Soft citrus"],
    description: "Decaffeinated using the Swiss Water Process — no chemical solvents, all the flavour. A gentle, rounded cup for any hour of the day.",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1000&q=80",
    format: "250g whole bean",
    altitude: "1,500–1,800m",
    process: "Swiss Water decaffeination"
  },
  {
    id: "bergkristall-cold-brew",
    sku: "BF-FIL-006",
    name: "Bergkristall Cold Brew Blend",
    category: "filter",
    roast: "medium",
    price: 14.20,
    origin: "Blend — Guatemala & Brazil",
    rating: 4.7,
    ratingCount: 121,
    notes: ["Dark cherry", "Vanilla", "Smooth cocoa"],
    description: "Coarse-ground and slow-roasted specifically for cold extraction — low acidity, naturally sweet, and just as good hot.",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1000&q=80",
    format: "250g coarse ground",
    altitude: "1,000–1,600m",
    process: "Natural blend"
  }
];

function bfGetProduct(id) {
  return PRODUCTS.find(function (p) { return p.id === id; });
}
